# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "paintingdreams"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.ssh.insert_key = false
  config.vm.provision "file", source: "keys/testkey.pub", destination: "~/.ssh/authorized_keys"
  config.ssh.private_key_path = ["keys/testkey", "~/.vagrant.d/insecure_private_key"]
  config.vm.synced_folder "../virtualenv", "/var/virtualenvs/paintingdreams"
  config.vm.synced_folder "../paintingdreams", "/var/www/paintingdreams.co.uk"
end
