# Generated by Django 2.2.17 on 2021-05-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0004_order_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='display_vat_message',
            field=models.BooleanField(default=True),
        ),
    ]
