# Generated by Django 2.2.17 on 2021-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0005_special_display_vat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='display_brexit_message',
            field=models.BooleanField(default=False),
        ),
    ]
