# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-11-30 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import mainapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Gallery')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HolidayMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('website_message', models.TextField(blank=True)),
                ('email_message', models.TextField(blank=True)),
                ('wholesale_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start', '-end'],
            },
        ),
        migrations.CreateModel(
            name='HomePageWebimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webimage', models.ImageField(upload_to=mainapp.models.get_webimage_path)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sizes', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('original', models.CharField(choices=[('notavailable', 'Not available'), ('available', 'Available'), ('sold', 'Sold')], default='notavailable', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Gallery')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Image')),
            ],
            options={
                'ordering': ['gallery', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImageWebimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webimage', models.ImageField(upload_to=mainapp.models.get_webimage_path)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sizes', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webimages', to='mainapp.Image')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('shipping_name', models.CharField(blank=True, max_length=100, null=True)),
                ('postage_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('state', models.CharField(choices=[('notpaid', 'Not paid'), ('paid', 'Paid'), ('shipped', 'Order shipped')], default='notpaid', max_length=18)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('address3', models.CharField(blank=True, max_length=255)),
                ('address4', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('post_code', models.CharField(blank=True, max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_weight', models.IntegerField()),
                ('quantity', models.SmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_processor', models.CharField(choices=[('paypal', 'PayPal'), ('cardsave', 'CardSave')], max_length=8)),
                ('state', models.CharField(choices=[('started', 'Started'), ('cancelled', 'Cancelled'), ('complete', 'Complete'), ('failed', 'Failed')], default='started', max_length=18)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Order', to_field='unique_id')),
            ],
        ),
        migrations.CreateModel(
            name='PostagePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('GB', 'United Kingdom'), ('EUROPE', 'Europe'), ('WORLD', 'Worldwide')], max_length=6)),
                ('min_weight', models.PositiveSmallIntegerField(default=0)),
                ('max_weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'ordering': ['destination', 'min_weight'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('hidden', models.BooleanField(default=False)),
                ('sold_out', models.BooleanField(default=False)),
                ('more_due', models.BooleanField(default=True)),
                ('due_text', models.CharField(blank=True, max_length=255)),
                ('extra_description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_type_order', models.IntegerField(default=0)),
                ('temporarily_unavailable', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Image')),
            ],
            options={
                'ordering': ['product_type_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductAdditionalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_product', to='mainapp.Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('displayname', models.CharField(blank=True, max_length=100)),
                ('inherit_displayname', models.BooleanField(default=False)),
                ('subproduct_hide', models.BooleanField(default=False)),
                ('index_inline', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('inherit_description', models.BooleanField(default=False)),
                ('product_listing_message', models.TextField(blank=True)),
                ('stand_alone', models.BooleanField(default=False)),
                ('inherit_stand_alone', models.BooleanField(default=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('inherit_price', models.BooleanField(default=True)),
                ('shipping_weight', models.IntegerField(default=0)),
                ('inherit_shipping_weight', models.BooleanField(default=False)),
                ('shipping_weight_multiple', models.IntegerField(default=0)),
                ('inherit_shipping_weight_multiple', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductType')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductTypeAdditionalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='ProductWebimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webimage', models.ImageField(upload_to=mainapp.models.get_webimage_path)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sizes', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webimages', to='mainapp.Product')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductType'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='mainapp.ProductTag'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_billing_address', to='mainapp.OrderAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_address', to='mainapp.OrderAddress'),
        ),
        migrations.AddField(
            model_name='image',
            name='galleries',
            field=models.ManyToManyField(through='mainapp.ImageGallery', to='mainapp.Gallery'),
        ),
        migrations.AddField(
            model_name='image',
            name='products',
            field=models.ManyToManyField(through='mainapp.Product', to='mainapp.ProductType'),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='mainapp.ImageTag'),
        ),
        migrations.AlterIndexTogether(
            name='holidaymessage',
            index_together=set([('start', 'end')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('image', 'product_type')]),
        ),
    ]
