# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-13 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_stock_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('view_order', 'Can view orders'),)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_type_order'], 'permissions': (('change_product_stock_count', 'Can change product stock count'),)},
        ),
    ]
