# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200113_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('dates', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FestivalPageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('festival_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FestivalPage')),
            ],
            options={
                'ordering': ['festival_page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FestivalPageWebimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webimage', models.ImageField(upload_to=mainapp.models.get_webimage_path)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sizes', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('festival_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webimages', to='mainapp.FestivalPage')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['image__title', 'product_type__title'], 'permissions': (('change_product_stock_count', 'Can change product stock count'),)},
        ),
        migrations.AddField(
            model_name='festivalpageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
        migrations.AddField(
            model_name='festivalpage',
            name='products',
            field=models.ManyToManyField(through='mainapp.FestivalPageProduct', to='mainapp.Product'),
        ),
    ]
