# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-27 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200126_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpage',
            name='short_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
