# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-14 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_festivalpage_short_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order'], 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'ordering': ['gallery', 'order'], 'verbose_name_plural': 'Image galleries'},
        ),
    ]
