# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_model_plural_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postageprice',
            name='destination',
            field=models.CharField(choices=[('GB', 'United Kingdom'), ('EUROPE', 'Europe'), ('WORLD', 'Worldwide'), ('US', 'United States')], max_length=6),
        ),
    ]
