# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_us_postage_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeDestinationShippingWeightOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('GB', 'United Kingdom'), ('EUROPE', 'Europe'), ('WORLD', 'Worldwide'), ('US', 'United States')], max_length=6)),
                ('shipping_weight', models.IntegerField(default=0)),
                ('shipping_weight_multiple', models.IntegerField(default=0)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_shipping_weight_overrides', to='mainapp.ProductType')),
            ],
            options={
                'verbose_name': 'destination shipping weight override',
            },
        ),
        migrations.AlterUniqueTogether(
            name='producttypedestinationshippingweightoverride',
            unique_together=set([('product_type', 'destination')]),
        ),
    ]
