# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-09-29 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_product_type_destination_weight_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('disabled', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCodeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.DiscountCode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='discountcodeproduct',
            unique_together=set([('discount_code', 'product')]),
        ),
    ]
