# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-09-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_add_order_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='discounted',
            field=models.BooleanField(default=False),
        ),
    ]
