# Generated by Django 2.2.16 on 2020-10-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_home_page_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
