# Generated by Django 2.2.17 on 2020-12-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_special_offer_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='old_price',
            new_name='special_offer_price',
        ),
    ]
