# Generated by Django 2.2.17 on 2021-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_new_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uk_only',
            field=models.BooleanField(default=False, verbose_name='UK orders only'),
        ),
    ]
