# Generated by Django 2.2.17 on 2021-03-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mainapp.Feedback')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='mainapp.Product')),
            ],
            options={
                'unique_together': {('feedback', 'product')},
            },
        ),
    ]
