# Generated by Django 2.2.17 on 2021-03-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_feedback_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='show_date',
            field=models.BooleanField(default=False),
        ),
    ]
