# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_producttype_index_inline'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewebimage',
            name='sizes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productwebimage',
            name='sizes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
