# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20170128_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postageprice',
            options={'ordering': ['destination', 'min_weight']},
        ),
    ]
