# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20170209_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='original_sold',
            field=models.BooleanField(default=False),
        ),
    ]
