# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20170212_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='original_available',
        ),
        migrations.RemoveField(
            model_name='image',
            name='original_sold',
        ),
        migrations.AddField(
            model_name='image',
            name='original',
            field=models.CharField(choices=[('notavailable', 'Not available'), ('available', 'Available'), ('sold', 'sold')], default='notavailable', max_length=15),
        ),
    ]
