# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20170213_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.CharField(choices=[('notavailable', 'Not available'), ('available', 'Available'), ('sold', 'Sold')], default='notavailable', max_length=15),
        ),
    ]
