# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20170213_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='message',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
