# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_ordertransaction_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['gallery', 'order'],
            },
        ),
        migrations.RenameModel(
            old_name='ImageTag',
            new_name='Gallery',
        ),
        migrations.RemoveField(
            model_name='imageimagetag',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imageimagetag',
            name='image_tag',
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ImageImageTag',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Gallery'),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='galleries',
            field=models.ManyToManyField(through='mainapp.ImageGallery', to='mainapp.Gallery'),
        ),
    ]
