# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20170304_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageWebimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webimage', models.ImageField(upload_to=mainapp.models.get_webimage_path)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sizes', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('link', models.SlugField(blank=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
