# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_homepagewebimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagewebimage',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
