# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_auto_20170319_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='inherit_shipping_weight_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttype',
            name='shipping_weight_multiple',
            field=models.IntegerField(default=0),
        ),
    ]
