# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20170515_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagewebimage',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
