# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-22 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_producttypeadditionalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
