# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-11 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_producttype_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='temporarily_unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
