# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-16 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_product_temporarily_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
