# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-08 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_product_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='secondary_type_displayname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producttype',
            name='secondary_type_inherit_displayname',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttype',
            name='secondary_type_inherit_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='secondary_type_inherit_shipping_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttype',
            name='secondary_type_inherit_shipping_weight_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttype',
            name='secondary_type_old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='producttype',
            name='secondary_type_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='producttype',
            name='secondary_type_shipping_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producttype',
            name='secondary_type_shipping_weight_multiple',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producttype',
            name='secondary_type_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
