# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-09 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_product_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdditionalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_product', to='mainapp.Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
        ),
    ]
