# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-15 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_productadditionalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overridden_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
