# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-08 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_auto_20190808_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='secondary_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_product_type_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
