# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-20 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_product_overridden_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_sale_price',
            field=models.BooleanField(default=True),
        ),
    ]
