# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-20 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_product_show_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='show_sale_price',
            new_name='show_old_price',
        ),
    ]
